"A datetime string with format `Y-m-d H:i:s`, e.g. `2018-05-23 13:43:32`."
scalar DateTime @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\DateTime")

"Indicates what fields are available at the top level of a query operation."

type Query {
    me: User @guard 
    task(id: ID!): Task @field(resolver: "App\\GraphQL\\Queries\\TaskQuery@task")
    tasks(first: Int!, page: Int): [Task!]! @paginate(model: "App\\Models\\Task", defaultCount: 10)
}

type ApiResponse {
    success: Boolean!
    message: String!
    status_code: Int
}

type Mutation {
    signin(email: String!, password: String!): Auth @field(resolver: "AuthMutation@signin")
  
    createTask(
      title: String!,
      status: String!,
      due_date: String!,
      description: String
    ): Task @guard(with: ["api"]) @field(resolver: "App\\GraphQL\\Mutations\\TaskMutation@create")

    deleteTask(id: ID!): ApiResponse @guard(with: ["api"]) @field(resolver: "App\\GraphQL\\Mutations\\TaskMutation@delete")

}

type Task {
    id: ID!
    title: String!
    status: String!
    description: String
    due_date: String!
    user_id: ID!
    json_response: JSON
}

type Auth {
    success: Boolean!
    message: String!
    token: String
    user: User
}

type User {
    id: ID!
    name: String!
    email: String!
    created_at: String!
    updated_at: String!
}

